os:
  - linux
  - osx

language: cpp

script:
  - cmake .
  - make

compiler:
  - clang
  - gcc

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./travis/linux.install.sh; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./travis/osx.install.sh; fi
